import Head from 'next/head'
import { useAuthState } from 'react-firebase-hooks/auth';
import SignIn from '../Components/Auth/SignIn';
import SignOut from '../Components/Auth/SignOut';
import ChatRoom from '../Components/Container/ChatRoom';
import Login from '../Components/Container/Login';
import styles from '../styles/Home.module.css'
import { auth } from './_app';

export default function Home() {
  const [user] = useAuthState(auth);


  return (
    <div className={styles.container}>
      <Head>
        <title>Chatroom App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen min-h-screen">
        {user ? <ChatRoom /> : <Login />}
        <SignOut />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
